name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into Droplet and pull code
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.DROPLET_IP }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.DROPLET_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: ssh ${{ steps.ssh.outputs.SERVER }} pwd
     
      - name: Add and commit changes
        run: |
          cd /path/to/your/repository
          git config user.name "Your Name"
          git config user.email "your.email@example.com"
          git add README.md
          git commit -m "Update README.md"
          git push origin main
