name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          
      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: |
          cd ./webapp
          npm ci

      - name: Build app
        run: |
          cd ./webapp
          npm run build
          ls -la

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          key_type: rsa
          script: |
            set -e
            cd /var/www/html
            echo "Current directory: $(pwd)"
            ls -la
            sudo rm -rf *


      - name: Run a multi-line script
        run: |          
          cd ./webapp
          cp -R package.json ./build/          
          cp -R /src/index.js ./build/          
          tar -cvf deploy.tar ./build/

      - name: Copy files to DigitalOcean droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "deploy.tar"
          target: '/var/www/html'

#       - name: Redirect copy to nginx root
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.DROPLET_IP }}
#           username: ${{ secrets.DROPLET_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           port: ${{ secrets.SSH_PORT }}
#           key_type: rsa
#           script: |
#             cd /var/www/html/github/workspace/webapp/build
#             echo "Current directory: $(pwd)"
#             cp -R * /var/www/html
#             rm -r /var/www/html/github

      - name: Set up PM2 process manager
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          key_type: rsa
          script: npm run start-pm


      - name: Clean up previous deployment
        run: |
          ls -t /var/www/html | tail -n +6 | xargs -I {} rm -rf /var/www/html/{}

      - name: Restart web server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          key_type: rsa
          script: |
            sudo systemctl restart nginx
