name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into Droplet and pwd
        id: ssh
        uses: invi5h/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_IP }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run command on Droplet
        run: |
          ssh -p ${{ secrets.SSH_PORT }} -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }} pwd

      - name: Create a git repository
        run: |
          cd /main/stage
          echo "# resoledge.com" >> README.md
          git init
          git add README.md
          git commit -m "first commit"
          git branch -M main
          git remote add origin https://github.com/chidi150c/resoledge.com.git
