name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into Droplet and git
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          key_type: rsa
          script: |
            echo "# resoledge.com" >> README.md

#       - name: Create a git repository
#         run: |
#           cd $GITHUB_WORKSPACE/resoledge.com/main/stage
#           echo "# resoledge.com" >> README.md
#           git init
#           git add README.md
#           git commit -m "first commit"
#           git branch -M main
#           git remote add origin https://github.com/chidi150c/resoledge.com.git
